name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  
    inputs:  
      create_release:  
        description: 'Create actual release'  
        required: false  
        default: 'false'
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        include:  
          - target: x86_64-unknown-linux-gnu  
            artifact: blockdiff-x86_64  
    steps:  
      - uses: actions/checkout@v4  
      - name: Install cross-compilation tools  
        if: matrix.target == 'aarch64-unknown-linux-gnu'  
        run: sudo apt-get install -y gcc-aarch64-linux-gnu  
      - uses: dtolnay/rust-toolchain@stable
        with:  
          toolchain: stable  
          targets: ${{ matrix.target }}  
      - run: cargo build --release --target ${{ matrix.target }}  
      - run: mv target/${{ matrix.target }}/release/blockdiff ${{ matrix.artifact }}
        #      - uses: actions/upload-artifact@v4
        #        with:
        #          name: ${{ matrix.artifact}}
        #          path: ${{ matrix.artifact}}
      - uses: softprops/action-gh-release@v1
        with:
          files: target/release/blockdiff-*
